let numero = 5


/**
 NUMERO PRIMO É QUE A SOBRA DA SUA DIVISÃO É INTEIRA APENAS QUANDO ELE É DIVIDIDO POR 1 E POR ELE MESMO
 EXEMPLO: 3
 3 / 3 = 1
 3 / 1 = 3
 3 / 2 = 1,5 O RESULTADO DA DIVISÃO TEM QUE SER DE UM NUMERO INTEIRO

 4 / 4 = 1
 4 / 2 = 2
 */